package generator.domain

import org.ktorm.database.Database
import org.ktorm.entity.Entity
import org.ktorm.entity.sequenceOf
import org.ktorm.schema.*
    
    

/**
* generated by KtormGenerator
* @date 2024-02-12
*/
interface Account : Entity<Account> {
    companion object : Entity.Factory<Account>()
    /**
     * 账号
     */
    var account: Long
    /**
     * 密码
     */
    var password: String
    /**
     * 权限
     */
    var authority: String
}

object Accounts : Table<Account>("account") {
    val account = long("account").primaryKey().bindTo { it.account }
    val password = varchar("password").bindTo { it.password }
    val authority = varchar("authority").bindTo { it.authority }
}



val Database._accounts get() = this.sequenceOf(Accounts)
