package generator.domain

import org.ktorm.database.Database
import org.ktorm.entity.Entity
import org.ktorm.entity.sequenceOf
import org.ktorm.schema.*
    
    

/**
* generated by KtormGenerator
* @date 2024-02-12
*/
interface Tblfininstitutionbasicinfo : Entity<Tblfininstitutionbasicinfo> {
    companion object : Entity.Factory<Tblfininstitutionbasicinfo>()
    var iId: Long
    var iName: String?
    var ownershipID: String?
    var property: String?
    var area: String?
    var responsiblePerson: String?
    var tel: String?
    var shareholderID: String?
}

object Tblfininstitutionbasicinfos : Table<Tblfininstitutionbasicinfo>("tblfininstitutionbasicinfo") {
    val iId = long("i_id").primaryKey().bindTo { it.iId }
    val iName = varchar("i_name").bindTo { it.iName }
    val ownershipID = varchar("ownershipID").bindTo { it.ownershipID }
    val property = varchar("property").bindTo { it.property }
    val area = varchar("area").bindTo { it.area }
    val responsiblePerson = varchar("responsiblePerson").bindTo { it.responsiblePerson }
    val tel = varchar("tel").bindTo { it.tel }
    val shareholderID = varchar("shareholderID").bindTo { it.shareholderID }
}



val Database._tblfininstitutionbasicinfos get() = this.sequenceOf(Tblfininstitutionbasicinfos)
