package generator.domain

import org.ktorm.database.Database
import org.ktorm.entity.Entity
import org.ktorm.entity.sequenceOf
import org.ktorm.schema.*
    
    

/**
* generated by KtormGenerator
* @date 2024-02-12
*/
interface Tbltime : Entity<Tbltime> {
    companion object : Entity.Factory<Tbltime>()
    var timeDimensionId: Long
    var year: Int?
    var quarter: Int?
}

object Tbltimes : Table<Tbltime>("tbltime") {
    val timeDimensionId = long("time_dimension_id").primaryKey().bindTo { it.timeDimensionId }
    val year = int("year").bindTo { it.year }
    val quarter = int("quarter").bindTo { it.quarter }
}



val Database._tbltimes get() = this.sequenceOf(Tbltimes)
